# -- OMIM cache - loaded once per session --------------------------------------
# Call .omim_cache_reset() to force reload (e.g. after updating the file)
.clinprior_cache <- new.env(parent = emptyenv())
.clinprior_cache$omim <- NULL

.get_omim_dt <- function(package = "ClinPrior") {
  if(!is.null(.clinprior_cache$omim)) return(.clinprior_cache$omim)
  omim_file <- file.path(system.file("extdata", package = package),
                         "OMIMphenotype_UCSCtable.txt")
  if(!file.exists(omim_file)) {
    message("Warning: OMIMphenotype_UCSCtable.txt not found - knownDiseaseLabel will be empty")
    return(data.table(approvedGeneSymbol = character(), phenotype = character()))
  }
  dt <- fread(omim_file, sep = "\t", header = TRUE, quote = "", fill = TRUE)
  dt <- dt[, .(
    approvedGeneSymbol = hg38.omim2gene.approvedGeneSymbol,
    phenotypeId        = hg38.omimPhenotype.phenotypeId,
    phenotype          = hg38.omimGeneMap2.phenotypes
  )]
  dt <- dt[!is.na(approvedGeneSymbol) & approvedGeneSymbol != "" &
             !is.na(phenotype)         & phenotype          != "" &
             !is.na(phenotypeId)       & phenotypeId        != ""]
  dt <- unique(dt, by = "phenotypeId")
  dt <- dt[, .(phenotype = paste(phenotype, collapse = " | ")), by = approvedGeneSymbol]
  .clinprior_cache$omim <- dt
  dt
}

.omim_cache_reset <- function() {
  .clinprior_cache$omim <- NULL
  invisible(NULL)
}

# -- Main function --------------------------------------------------------------
#' Prioritize variants using clinical and phenotypic evidence
#'
#' @description
#' Main function of ClinPrior. Filters and scores genetic variants by integrating
#' variant pathogenicity (VEP consequence, CADD, splicing), gene constraint metrics
#' (pLI, pRec, lof_z, mis_z, C1KB), inheritance mode (HOM, HET, CmpHET, XLink),
#' and phenotypic similarity scores. Returns a ranked table with a diagnostic
#' closure \code{traceVariant} attached as an attribute.
#'
#' @param variants A \code{data.frame} generated by \code{readVCF()}, with a
#'   \code{vcfFile} attribute pointing to the original VCF file.
#' @param sampleName Character. Sample identifier used for labelling outputs.
#' @param filter Character. Optional variant filter string. Default \code{""}.
#' @param isCodingVar Logical. If \code{TRUE} (default), restricts analysis to
#'   protein-coding variants (\code{BIOTYPE == "protein_coding"}).
#' @param frequenceAR Numeric. Maximum gnomAD allele frequency allowed for
#'   autosomal recessive candidates (HOM, CmpHET, XLink). Default \code{0.01}.
#' @param frequenceAD Numeric. Maximum gnomAD allele frequency allowed for
#'   autosomal dominant candidates (HET). Default \code{0.00005}.
#' @param GlobalPhenotypicScore Matrix with phenotypic similarity scores per gene,
#'   as returned by \code{MatrixPropagation()}. Must contain functional (cols 2-3) and
#'   physical (cols 5-6) score columns.
#' @param assembly Character. Genome assembly version. Either \code{"assembly38"}
#'   (default, hg38) or \code{"assembly37"} (hg19). C1KB constraint z-scores are
#'   only available for \code{"assembly38"}.
#' @param freqInterna Numeric. Maximum allele frequency in the internal cohort
#'   frequency file. Default \code{0.4}.
#' @param nCalledMin Integer. Minimum number of called samples in the internal
#'   cohort required to apply the frequency filter. Default \code{10}.
#' @param nAllelesMax Integer. Maximum number of different alleles at the same
#'   position in the internal cohort dictionary. Positions with more than
#'   \code{nAllelesMax} entries are considered hypervariable (e.g. STR/microsatellites)
#'   and discarded regardless of REF/ALT match. Default \code{5}.
#' @param discard_ClinVar_Benign Logical. If \code{TRUE} (default), removes variants
#'   annotated as benign or likely_benign in ClinVar, unless also annotated as
#'   pathogenic or likely_pathogenic.
#' @param freqInternaFile Character. Path to a bgzipped, tabix-indexed TSV file
#'   with internal cohort allele frequencies. Set to \code{NULL} to skip.
#' @param splicingMode Character. Splicing evaluation strategy. \code{"vep"} uses
#'   MaxEntScan scores from the VEP annotation (30 bp boundary only). \code{"full"}
#'   additionally calls \code{MaxentScanClinPrior()} for intronic variants
#'   within \code{splicingDistance} bp of the exon boundary. Default \code{"vep"}.
#' @param splicingDistance Integer. Maximum distance (bp) from the exon-intron
#'   boundary for intronic variants to be evaluated in \code{splicingMode = "full"}.
#'   Default \code{1000}.
#' @param splicingWorkers Integer. Number of parallel workers used by
#'   \code{MaxentScanClinPrior()} in \code{splicingMode = "full"}. Default \code{8}.
#' @param discard_zero_score Logical. If \code{TRUE}, removes rows where
#'   \code{VariantScore == 0} from the final output table. Default \code{FALSE}.
#'
#' @return A \code{data.frame} of prioritized variants sorted by \code{OrderScore}
#'   (descending), with a \code{ClinPriorPosition} rank column prepended. The
#'   attribute \code{traceVariant} contains a diagnostic closure that can be called
#'   as \code{attr(result, "traceVariant")(chrom, pos, ref, alt)} to inspect
#'   filters and scores for any individual variant.
#'
#' @export
#' @importFrom data.table fread data.table setkey setkeyv foverlaps
#' @importFrom stringi stri_replace_first_regex stri_split_fixed stri_list2matrix
#' @importFrom BiocParallel bplapply
#' @importFrom stats ave
#'
#' @examples
#' \dontrun{
#' variants <- readVCF("sample.vep.vcf.gz", sampleName = "sample1",
#'                     assembly = "assembly38", geneQuality = 20,
#'                     readDepth = 10, distSplicThreshold = "vep",
#'                     synonymous = TRUE)
#'
#' HPOpatient <- c("HP:0004481", "HP:0002376", "HP:0001257", "HP:0001250",
#'                 "HP:0000238", "HP:0002922", "HP:0000365")
#' Y                     <- proteinScore(HPOpatient)
#' GlobalPhenotypicScore <- MatrixPropagation(Y$scores, alpha = 0.2)
#'
#' results <- priorBestVariant(variants, sampleName = "sample1",
#'                             GlobalPhenotypicScore = GlobalPhenotypicScore)
#'
#' # Inspect a specific variant:
#' attr(results, "traceVariant")("chr1", 123456, "A", "T")
#' }
priorBestVariant <- function(variants, sampleName, filter="", isCodingVar=TRUE,
                             frequenceAR=0.01, frequenceAD=0.00005,
                             GlobalPhenotypicScore, assembly="assembly38",
                             freqInterna=0.05, nCalledMin=10, nAllelesMax=5,
                             discard_ClinVar_Benign=TRUE,
                             freqInternaFile=NULL,
                             # -- Splicing mode ------------------------------------------------------
                             # "vep"  : uses MaxEntScan_diff/ref/alt from the VCF (default, +-30bp boundary)
                             # "full" : calls MaxentScanClinPrior for:
                             #            - intronic variants <= splicingDistance bp from the boundary (HGVSc)
                             #            - those that already had Splicing != || from VEP
                             splicingMode     = "vep",
                             splicingDistance = 1000,  # maximum distance to the boundary for intronic variants
                             splicingWorkers  = 8,     # number of parallel workers for "full" mode
                             # -- Output filters -----------------------------------------------------
                             # discard_zero_score: if TRUE (default FALSE), removes rows where
                             #   VariantScore == 0 from the final table.
                             discard_zero_score = FALSE
) {
  
  # Initialise reticulate in the main process BEFORE starting workers
  if(splicingMode == "full") {
    requireNamespace("reticulate", quietly = TRUE)
    reticulate::py_config()
  }
  
  assembly <<- assembly
  dest <- system.file(paste("extdata", assembly, sep="/"), package="ClinPrior")
  ClinPriorfiles <- list.files(path=dest, full.names=TRUE)
  constrains1KB  <- ClinPriorfiles[grep("constraint_z_genome_1kb.qc.download.txt.gz", ClinPriorfiles, perl=TRUE)]
  
  # -- OMIM phenotype table (cached across calls) ----------------------------
  omim_dt <- .get_omim_dt()
  
  # -- Read CSQ metadata automatically from the VCF -------------------------
  vcfFile <- attr(variants, "vcfFile")
  if(is.null(vcfFile)) stop("The data.frame has no 'vcfFile' attribute. Make sure to use readVCF() to generate it.")
  hdr_csq <- system(paste0("bcftools view -h ", vcfFile, " | grep 'ID=CSQ'"), intern=TRUE)
  meta    <- strsplit(gsub('.*Format: ([^"]+)".*', "\\1", hdr_csq), "[|]")[[1]]
  
  # -- Parse CSQ only once ---------------------------------------------------
  csq_raw   <- stri_replace_first_regex(variants$INFO, ".*CSQ=", "")
  csq_first <- stri_replace_first_regex(csq_raw, ",.*", "")
  csq_split <- stri_split_fixed(csq_first, "|")
  # INFO column is no longer needed - free it before the heavy field extraction
  variants$INFO <- NULL
  gc()
  
  gene_pos        <- match("Gene",           meta)
  consequence_pos <- match("Consequence",    meta)
  impact_pos      <- match("IMPACT",         meta)
  cdna_pos        <- match("HGVSc",          meta)
  prot_pos        <- match("HGVSp",          meta)
  biotype_pos     <- match("BIOTYPE",        meta)
  af_pos          <- match("AF",             meta)
  gnomadg_pos     <- match("gnomADg_AF",     meta)
  gnomade_pos     <- match("gnomADe_AF",     meta)
  clinvar_pos     <- match("CLIN_SIG",       meta)
  cadd_pos        <- match("CADD_PHRED",     meta)
  maxent_diff_pos <- match("MaxEntScan_diff", meta)
  maxent_ref_pos  <- match("MaxEntScan_ref",  meta)
  maxent_alt_pos  <- match("MaxEntScan_alt",  meta)
  
  # FIX: protect getField against NA positions (field absent from VCF)
  getField <- function(pos) {
    if(is.na(pos)) return(rep(NA_character_, nrow(variants)))
    stri_list2matrix(lapply(csq_split, `[`, pos), byrow=TRUE)[,1]
  }
  
  gene        <- getField(gene_pos)
  consequence <- getField(consequence_pos)
  impact      <- getField(impact_pos)
  cdna        <- getField(cdna_pos)
  protein     <- getField(prot_pos)
  biotype     <- getField(biotype_pos)
  clinvar     <- getField(clinvar_pos)
  cadd        <- suppressWarnings(as.numeric(getField(cadd_pos)))
  
  af1    <- suppressWarnings(as.numeric(getField(af_pos)))
  af2    <- suppressWarnings(as.numeric(getField(gnomadg_pos)))
  af3    <- suppressWarnings(as.numeric(getField(gnomade_pos)))
  gnomAD <- pmax(af1, af2, af3, na.rm=TRUE)
  
  # -- Splicing VEP ----------------------------------------------------------
  me_diff <- suppressWarnings(as.numeric(getField(maxent_diff_pos)))
  me_ref  <- suppressWarnings(as.numeric(getField(maxent_ref_pos)))
  me_alt  <- suppressWarnings(as.numeric(getField(maxent_alt_pos)))
  pct_imp <- abs(me_diff / me_ref)
  splicing_vep <- ifelse(!is.na(pct_imp) & pct_imp >= 0.2,
                         paste(me_diff, me_ref, me_alt, sep="|"),
                         "||")
  # -- Free large CSQ intermediates ------------------------------------------
  rm(csq_raw, csq_first, csq_split, hdr_csq,
     af1, af2, af3, me_diff, me_ref, me_alt, pct_imp)
  gc()
  
  ensembl_id  <- gene
  gene_symbol <- totalEnsembl[match(ensembl_id, totalEnsembl[,3]), 1]
  gene_name   <- totalEnsembl[match(ensembl_id, totalEnsembl[,3]), 2]
  
  HIGH     <- ifelse(impact == "HIGH",     paste(cdna, protein, sep="|"), ".")
  MODERATE <- ifelse(impact == "MODERATE", paste(cdna, protein, sep="|"), ".")
  
  # -- Genotype --------------------------------------------------------------
  gt     <- variants$GT
  is_HOM <- gt %in% c("1/1","1|1","2/2","3/3") & variants$CHROM != "X"
  is_HET <- grepl("^0[/|][1-9]|^[1-9][/|]0", gt) & !is_HOM & variants$CHROM != "X"
  is_XL  <- variants$CHROM == "X" & !gt %in% c("0/0","0|0")
  
  is_coding <- biotype == "protein_coding"
  
  # -- Gene constraint metrics -----------------------------------------------
  metrics_idx <- match(gene_name, geneConstraints$gene)
  pLI   <- geneConstraints$pLI[metrics_idx]
  pRec  <- geneConstraints$pRec[metrics_idx]
  lof_z <- geneConstraints$lof_z[metrics_idx]
  mis_z <- geneConstraints$mis_z[metrics_idx]
  
  # -- 1KB constraint z-score (C1KB) - only available for assembly38 ---------
  C1KB <- rep(NA_real_, nrow(variants))
  
  if(assembly == "assembly38") {
    keep_base_pre <- if(isCodingVar) is_coding else rep(TRUE, nrow(variants))
    keep_gnomad   <- is.na(gnomAD) | gnomAD <= frequenceAR
    idx_c1kb_pre  <- which(keep_base_pre & keep_gnomad)
    
    if(length(idx_c1kb_pre) > 0) {
      var_chr_pre  <- as.character(variants$CHROM[idx_c1kb_pre])
      var_pos_pre  <- as.numeric(variants$POS[idx_c1kb_pre])
      var_chr_chr  <- ifelse(grepl("^chr", var_chr_pre), var_chr_pre, paste0("chr", var_chr_pre))
      regions_c1kb <- paste0(var_chr_chr, ":", var_pos_pre, "-", var_pos_pre)
      
      res_c1kb <- tryCatch(
        seqminer::tabix.read.table(constrains1KB, regions_c1kb),
        error = function(e) data.frame()
      )
      
      if(nrow(res_c1kb) > 0) {
        dt_ref <- data.table(
          chr   = as.character(res_c1kb[[1]]),
          start = as.numeric(res_c1kb[[2]]),
          end   = as.numeric(res_c1kb[[3]]),
          z     = as.numeric(res_c1kb[[9]])
        )
        dt_var <- data.table(
          chr   = var_chr_chr,
          start = var_pos_pre,
          end   = var_pos_pre,
          idx   = idx_c1kb_pre
        )
        setkey(dt_ref, chr, start, end)
        setkeyv(dt_var, c("chr", "start", "end"))
        ovlp <- foverlaps(dt_var, dt_ref,
                          by.x = c("chr","start","end"),
                          by.y = c("chr","start","end"),
                          nomatch = NA)
        hit_mean <- ovlp[!is.na(z), .(C1KB_val = z), by = idx]
        C1KB[hit_mean$idx] <- hit_mean$C1KB_val
      }
    }
  } else {
    message("C1KB constraint z-score not applied (only available for assembly38).")
  }
  
  # -- Internal allele frequency ---------------------------------------------
  if(!is.null(freqInternaFile) && !file.exists(freqInternaFile))
    stop("freqInternaFile not found: ", freqInternaFile)
  
  freqInterna_vec <- rep(NA_real_,    nrow(variants))
  nCalled_vec     <- rep(NA_real_,    nrow(variants))
  nAlleles_vec    <- rep(NA_integer_, nrow(variants))
  
  keep_base_pre <- if(isCodingVar) is_coding else rep(TRUE, nrow(variants))
  keep_gnomad   <- is.na(gnomAD) | gnomAD <= frequenceAR
  idx_pre       <- which(keep_base_pre & keep_gnomad)
  
  normChrom <- function(ch) {
    ch <- sub("^chr", "", ch)
    ch <- ifelse(ch %in% c("M", "MT"), "M", ch)
    paste0("chr", ch)
  }
  chrom_norm <- normChrom(variants$CHROM[idx_pre])
  regions    <- paste0(chrom_norm, ":", variants$POS[idx_pre], "-", variants$POS[idx_pre])
  
  res_freq <- if(!is.null(freqInternaFile)) {
    tryCatch(
      seqminer::tabix.read.table(freqInternaFile, regions),
      error = function(e) data.frame()
    )
  } else {
    data.frame()
  }
  
  if(nrow(res_freq) > 0) {
    res_chr <- as.character(res_freq[[1]])
    res_pos <- as.numeric(res_freq[[2]])
    
    # -- Posicions hipervariables (STR/microsatel.lits) ----------------------
    pos_key        <- paste(res_chr, res_pos, sep = "-")
    pos_key_counts <- table(pos_key)
    hypervar_keys  <- names(pos_key_counts[pos_key_counts > nAllelesMax])
    
    var_pos_key <- paste0(chrom_norm, "-", variants$POS[idx_pre])
    is_hypervar <- var_pos_key %in% hypervar_keys
    
    if(any(is_hypervar)) {
      message(sprintf(
        "  [freqInterna] %d variant(s) at hypervariable position discarded (>%d alleles in internal dictionary)",
        sum(is_hypervar), nAllelesMax
      ))
      freqInterna_vec[idx_pre[is_hypervar]] <- 1
      nCalled_vec[idx_pre[is_hypervar]]     <- nCalledMin + 1
    }
    
    alleles_col <- as.character(res_freq[[3]])
    is_hail_fmt <- any(grepl("^\\[", alleles_col, perl=TRUE))
    
    if(is_hail_fmt) {
      res_ref <- gsub('^\\["([^"]+)","[^"]+"\\]$', "\\1", alleles_col, perl=TRUE)
      res_alt <- gsub('^\\["[^"]+","([^"]+)"\\]$', "\\1", alleles_col, perl=TRUE)
    } else {
      res_ref <- alleles_col
      res_alt <- as.character(res_freq[[4]])
    }
    
    res_ac <- suppressWarnings(as.integer(res_freq[[4]]))
    res_an <- suppressWarnings(as.integer(res_freq[[5]]))
    res_af <- suppressWarnings(as.numeric(gsub(",", ".", res_freq[[6]])))
    res_nc <- suppressWarnings(as.numeric(res_freq[[7]]))
    
    res_key <- paste(res_chr, res_pos, res_ref, res_alt, sep="-")
    var_key <- paste0(chrom_norm, "-", variants$POS[idx_pre], "-",
                      variants$REF[idx_pre], "-", variants$ALT[idx_pre])
    
    pos_match <- match(var_key, res_key)
    has_match <- !is.na(pos_match)
    freqInterna_vec[idx_pre[has_match]] <- res_af[pos_match[has_match]]
    nCalled_vec[idx_pre[has_match]]     <- res_nc[pos_match[has_match]]
    nAlleles_vec[idx_pre[has_match]]    <- res_ac[pos_match[has_match]]
  }
  
  # FIX: nAlleles_vec (AC) no s'usa per filtrar - només per informació
  keep_freqInterna <- (is.na(freqInterna_vec) | is.na(nCalled_vec) |
                         nCalled_vec < nCalledMin |
                         freqInterna_vec <= freqInterna)
  
  # -- ClinVar Benign filter -------------------------------------------------
  if(discard_ClinVar_Benign) {
    is_benign    <- grepl("benign|likely_benign", clinvar, ignore.case=TRUE)
    is_pathog    <- grepl("^pathogenic|likely_pathogenic", clinvar, ignore.case=TRUE, perl=TRUE)
    keep_clinvar <- !is_benign | is_pathog
  } else {
    keep_clinvar <- rep(TRUE, nrow(variants))
  }
  
  # -- Base filters ----------------------------------------------------------
  keep_base <- if(isCodingVar) is_coding else rep(TRUE, nrow(variants))
  keep_AR   <- keep_base & (is.na(gnomAD) | gnomAD <= frequenceAR) & keep_freqInterna & keep_clinvar
  keep_AD   <- keep_base & (is.na(gnomAD) | gnomAD <= frequenceAD) & keep_freqInterna & keep_clinvar
  
  # -- Splicing mode "full" --------------------------------------------------
  acceptor_loss     <- rep(0,  nrow(variants))
  acceptor_loss_pos <- rep(NA, nrow(variants))
  acceptor_gain     <- rep(0,  nrow(variants))
  acceptor_gain_pos <- rep(NA, nrow(variants))
  donor_loss        <- rep(0,  nrow(variants))
  donor_loss_pos    <- rep(NA, nrow(variants))
  donor_gain        <- rep(0,  nrow(variants))
  donor_gain_pos    <- rep(NA, nrow(variants))
  dist_num          <- rep(NA_real_, nrow(variants))
  
  if(splicingMode == "full") {
    message(sprintf(
      "splicingMode='full': evaluating intronic variants <=%d bp from boundary...",
      splicingDistance
    ))
    
    keep_for_splicing <- keep_AR
    
    hgvsc_only <- gsub(".*:(c\\.[^|]+)", "\\1", cdna)
    dist_str   <- gsub(".*c\\.[0-9]+([+\\-][0-9]+).*", "\\1", hgvsc_only, perl=TRUE)
    has_match  <- grepl("c\\.[0-9]+[+\\-][0-9]+", hgvsc_only, perl=TRUE)
    dist_num[has_match] <- as.numeric(dist_str[has_match])
    
    is_intronic      <- grepl("intron", consequence, ignore.case=TRUE)
    near_boundary    <- !is.na(dist_num) & abs(dist_num) <= splicingDistance
    has_vep_splicing <- splicing_vep != "||"
    
    idx_full <- which(keep_for_splicing &
                        ((is_intronic & near_boundary) | has_vep_splicing))
    
    message(sprintf("  Selected %d variants:", length(idx_full)))
    message(sprintf("    - Intronic <= %d bp (HGVSc, no VEP splicing): %d",
                    splicingDistance,
                    sum(keep_for_splicing & is_intronic & near_boundary & !has_vep_splicing)))
    message(sprintf("    - With positive VEP splicing (already <= 30bp):  %d",
                    sum(keep_for_splicing & has_vep_splicing)))
    message(sprintf("    - TOTAL new relative to VEP:                     %d",
                    sum(keep_for_splicing & is_intronic & near_boundary & !has_vep_splicing)))
    
    if(length(idx_full) > 0) {
      mx_input <- variants[idx_full, c("CHROM","POS","REF","ALT")]
      mx_input$genesList <- gene_symbol[idx_full]
      
      valid_gene     <- !is.na(mx_input$genesList) & mx_input$genesList != ""
      idx_full_valid <- idx_full[valid_gene]
      mx_input       <- mx_input[valid_gene, ]
      
      if(nrow(mx_input) > 0) {
        mx_out <- MaxentScanClinPrior(
          matrixVariants = mx_input,
          assembly       = assembly,
          Threshold      = 0.2,
          chunk_size     = 250,
          workers        = splicingWorkers
        )
        
        acceptor_loss[idx_full_valid]     <- mx_out$acceptor_loss
        acceptor_loss_pos[idx_full_valid] <- mx_out$acceptor_loss_pos
        acceptor_gain[idx_full_valid]     <- mx_out$acceptor_gain
        acceptor_gain_pos[idx_full_valid] <- mx_out$acceptor_gain_pos
        donor_loss[idx_full_valid]        <- mx_out$donor_loss
        donor_loss_pos[idx_full_valid]    <- mx_out$donor_loss_pos
        donor_gain[idx_full_valid]        <- mx_out$donor_gain
        donor_gain_pos[idx_full_valid]    <- mx_out$donor_gain_pos
        
        is_intronic_valid <- is_intronic[idx_full_valid]
        dist_valid        <- dist_num[idx_full_valid]
        far_from_boundary <- is_intronic_valid & !is.na(dist_valid) & abs(dist_valid) > 25
        
        acceptor_loss[idx_full_valid[far_from_boundary]]     <- 0
        acceptor_loss_pos[idx_full_valid[far_from_boundary]] <- NA
        donor_loss[idx_full_valid[far_from_boundary]]        <- 0
        donor_loss_pos[idx_full_valid[far_from_boundary]]    <- NA
      }
    } else {
      message("  No variants selected for full splicing evaluation.")
    }
  }
  
  # -- Select active splicing field for VariantScore -------------------------
  splicing <- if(splicingMode == "vep") {
    splicing_vep
  } else {
    has_splicing_full <- acceptor_loss != 0 | acceptor_gain != 0 |
      donor_loss    != 0 | donor_gain    != 0
    ifelse(has_splicing_full,
           paste(round(acceptor_loss,2), round(acceptor_gain,2),
                 round(donor_loss,2),    round(donor_gain,2), sep="|"),
           "|||")
  }
  
  # -- PhenoScore ------------------------------------------------------------
  FunctPos   <- match(gene_name, GlobalPhenotypicScore[,2])
  PhysPos    <- match(gene_name, GlobalPhenotypicScore[,5])
  FunctScore <- as.numeric(GlobalPhenotypicScore[FunctPos, 3]); FunctScore[is.na(FunctScore)] <- 0.0001
  PhysScore  <- as.numeric(GlobalPhenotypicScore[PhysPos,  6]); PhysScore[is.na(PhysScore)]   <- 0.0001
  FunctPos[is.na(FunctPos)] <- nrow(GlobalPhenotypicScore)/2
  PhysPos[is.na(PhysPos)]   <- nrow(GlobalPhenotypicScore)/2
  
  # -- Known disease / inheritance mode lookup -------------------------------
  HPOrecessive <- "HP:0000007|HP:0001416|HP:0001526"
  HPOdominant  <- "HP:0000006|HP:0001415|HP:0001447|HP:0001448|HP:0001451|HP:0001455|HP:0001456|HP:0001463"
  HPOXlink     <- "HP:0001417|HP:0001418|HP:0001419|HP:0001423"
  rec_genes <- HPO2genes[grep(HPOrecessive, HPO2genes[,2]), 1]
  dom_genes <- HPO2genes[grep(HPOdominant,  HPO2genes[,2]), 1]
  xl_genes  <- HPO2genes[grep(HPOXlink,     HPO2genes[,2]), 1]
  
  getKnownDisease_vec <- function(gs) {
    kd <- rep("", length(gs))
    kd[gs %in% rec_genes] <- paste0(kd[gs %in% rec_genes], "|AR|")
    kd[gs %in% dom_genes] <- paste0(kd[gs %in% dom_genes], "|AD|")
    kd[gs %in% xl_genes]  <- paste0(kd[gs %in% xl_genes],  "|XLINK|")
    kd
  }
  
  # -- Vectorised VariantScore calculation -----------------------------------
  calcScore <- function(idx, inheritance) {
    s          <- rep(0, length(idx))
    hi         <- HIGH[idx] != "."
    mo         <- MODERATE[idx] != "."
    sp_vep_raw <- splicing_vep[idx] != "||"
    sp_full_raw <- splicing[idx] != "||" & splicing[idx] != "|||"
    sp         <- if(splicingMode == "full") sp_vep_raw | sp_full_raw else sp_full_raw
    cd         <- cadd[idx]
    c1kb       <- C1KB[idx]
    pl         <- pLI[idx];  lz <- lof_z[idx]
    pr         <- pRec[idx]; mz <- mis_z[idx]
    
    if(splicingMode == "full") {
      sp_vep       <- sp_vep_raw
      sp_full_only <- sp & !sp_vep_raw
    } else {
      sp_vep       <- sp
      sp_full_only <- rep(FALSE, length(idx))
    }
    
    # HIGH impact variants
    s[hi] <- s[hi] + 0.4
    s[hi & !is.na(pl) & pl > 0.9] <- s[hi & !is.na(pl) & pl > 0.9] + 0.2
    s[hi & !is.na(lz) & lz > 3]   <- s[hi & !is.na(lz) & lz > 3]   + 0.1
    s[hi & !is.na(cd) & cd >= 20]  <- s[hi & !is.na(cd) & cd >= 20] + 0.05
    s[hi & !is.na(cd) & cd >= 25]  <- s[hi & !is.na(cd) & cd >= 25] + 0.05
    s[hi & !is.na(cd) & cd >= 30]  <- s[hi & !is.na(cd) & cd >= 30] + 0.1
    
    # MODERATE impact variants (excluding splicing and HIGH)
    mo2 <- mo & !sp & !hi
    s[mo2] <- s[mo2] + 0.2
    s[mo2 & !is.na(pl) & pl > 0.9] <- s[mo2 & !is.na(pl) & pl > 0.9] + 0.1
    s[mo2 & !is.na(mz) & mz > 3]   <- s[mo2 & !is.na(mz) & mz > 3]   + 0.05
    s[mo2 & !is.na(cd) & cd >= 20]  <- s[mo2 & !is.na(cd) & cd >= 20] + 0.05
    s[mo2 & !is.na(cd) & cd >= 25]  <- s[mo2 & !is.na(cd) & cd >= 25] + 0.05
    s[mo2 & !is.na(cd) & cd >= 30]  <- s[mo2 & !is.na(cd) & cd >= 30] + 0.1
    
    # SPLICING VEP (score 0.2 - high confidence, within <=30bp of canonical boundary)
    sp2_vep <- sp_vep & !hi
    s[sp2_vep] <- s[sp2_vep] + 0.2
    s[sp2_vep & !is.na(pl) & pl > 0.9] <- s[sp2_vep & !is.na(pl) & pl > 0.9] + 0.1
    s[sp2_vep & !is.na(lz) & lz > 3]   <- s[sp2_vep & !is.na(lz) & lz > 3]   + 0.1
    s[sp2_vep & !is.na(cd) & cd >= 20]  <- s[sp2_vep & !is.na(cd) & cd >= 20] + 0.1
    s[sp2_vep & !is.na(cd) & cd >= 25]  <- s[sp2_vep & !is.na(cd) & cd >= 25] + 0.1
    s[sp2_vep & !is.na(cd) & cd >= 30]  <- s[sp2_vep & !is.na(cd) & cd >= 30] + 0.1
    
    # SPLICING full-only (score 0.05 - lower confidence, cryptic distant gains)
    sp2_full <- sp_full_only & !hi
    s[sp2_full] <- s[sp2_full] + 0.05
    
    # C1KB z-score bonus - only applied when assembly == "assembly38"
    if(assembly == "assembly38") {
      is_intron_var <- grepl("intron_variant", consequence[idx], ignore.case=TRUE)
      s[!is_intron_var & !is.na(c1kb) & c1kb >= 2.18] <- s[!is_intron_var & !is.na(c1kb) & c1kb >= 2.18] + 0.1
      s[!is_intron_var & !is.na(c1kb) & c1kb >= 4]    <- s[!is_intron_var & !is.na(c1kb) & c1kb >= 4]    + 0.15
      s[ is_intron_var & !is.na(c1kb) & c1kb >= 2.18] <- s[ is_intron_var & !is.na(c1kb) & c1kb >= 2.18] + 0.015
      s[ is_intron_var & !is.na(c1kb) & c1kb >= 4]    <- s[ is_intron_var & !is.na(c1kb) & c1kb >= 4]    + 0.035
    }
    
    # Inheritance-mode adjustments
    if(inheritance == "HOM") {
      is_mito <- variants$CHROM[idx] %in% c("MT", "chrM", "M")
      s[!is_mito] <- s[!is_mito] + 0.5
      s[!is.na(pr) & pr > 0.7] <- s[!is.na(pr) & pr > 0.7] + 0.1
    }
    if(inheritance == "CmpHET") {
      gene_sym_local <- gene_symbol[idx]
      vs_positive    <- s > 0
      vs_cadd_high   <- vs_positive & !is.na(cd) & cd >= 20
      dt_tmp         <- data.table(g  = gene_sym_local,
                                   vp = as.integer(vs_positive),
                                   vc = as.integer(vs_cadd_high))
      dt_agg         <- dt_tmp[, .(n_pos = sum(vp), n_cad = sum(vc)), by = g]
      dt_tmp         <- dt_agg[dt_tmp, on = "g"]
      apply_cmphet   <- !sp2_full & dt_tmp$n_pos >= 2 & dt_tmp$n_cad >= 1
      s[apply_cmphet] <- s[apply_cmphet] + 0.2
      s[apply_cmphet & !is.na(pr) & pr > 0.7] <-
        s[apply_cmphet & !is.na(pr) & pr > 0.7] + 0.05
    }
    if(inheritance == "HET") {
      c1kb_ok <- assembly == "assembly38" & !is.na(c1kb) & c1kb >= 2
      mask    <- !sp_vep & !hi & !c1kb_ok & (is.na(cd) | cd < 20)
      s[mask] <- s[mask] / 10
    }
    if(inheritance == "XLink") {
      s[gt[idx] == "0/1"] <- 0
    }
    
    # Zero out variants with no functional evidence
    s[!sp & !hi & !mo] <- 0
    round(s, 4)
  }
  
  # -- ClinPriorScore: integrates variant evidence with phenotypic score ------
  calcClinPrior <- function(VariantScore, idx, inheritance) {
    position  <- pmin(FunctPos[idx], PhysPos[idx])
    score     <- pmax(FunctScore[idx], PhysScore[idx])
    n         <- nrow(totalEnsembl)
    pos_score <- log10(1 + n - position) / log10(n)
    vs_max <- switch(inheritance,
                     HOM    = 1.75,
                     XLink  = 1.75,
                     CmpHET = 1.40,
                     HET    = 1.15,
                     1.75)
    vs_norm <- pmin(VariantScore / vs_max, 1)
    cp      <- (pos_score * score * vs_norm) ^ (1/3)
    cp[VariantScore == 0] <- 0
    list(cp = round(cp, 4), vs_norm = round(vs_norm, 4))
  }
  
  # -- Physical phasing initialisation ---------------------------------------
  phase_id_full  <- rep(NA_character_, nrow(variants))
  cis_phased_out <- rep(FALSE, nrow(variants))
  
  # FIX: Omplir phaseGT per TOTS els HET ABANS de constructTable
  # Permet veure el PID a la columna phaseGT fins i tot per variants que
  # han estat eliminades del CmpHET per CIS (surten com HET a la taula final)
  het_all_idx <- which(is_HET)
  if(length(het_all_idx) > 0) {
    gt_full_all <- if(!is.null(variants$GT_full)) variants$GT_full[het_all_idx] else variants$GT[het_all_idx]
    m_pid_all   <- regexpr("\\d+_[ACGT*]+_[ACGT*]+", gt_full_all, perl=TRUE)
    has_pid_all <- m_pid_all > 0
    phase_id_full[het_all_idx[has_pid_all]] <- regmatches(gt_full_all, m_pid_all)
  }
  
  # -- CmpHET candidate pool -------------------------------------------------
  het_idx_all <- which(is_HET & keep_AR)
  
  cmphet_gene_all <- gene_symbol[het_idx_all]
  null_pos_all    <- which(is.na(cmphet_gene_all) | cmphet_gene_all == "")
  if(length(null_pos_all) > 0) {
    het_idx_all     <- het_idx_all[-null_pos_all]
    cmphet_gene_all <- cmphet_gene_all[-null_pos_all]
  }
  dup_genes_all <- names(table(cmphet_gene_all)[table(cmphet_gene_all) >= 2])
  cmphet_idx    <- het_idx_all[cmphet_gene_all %in% dup_genes_all]
  
  # X-linked variants are excluded from CmpHET
  cmphet_idx <- cmphet_idx[grep("\\bX\\b", variants$CHROM[cmphet_idx], invert=TRUE)]
  
  # -- Build output table for a set of variant indices and inheritance mode ---
  constructTable <- function(idx, inheritance) {
    if(length(idx) == 0) return(NULL)
    
    vs      <- calcScore(idx, inheritance)
    cp_list <- calcClinPrior(vs, idx, inheritance)
    cp      <- cp_list$cp
    vs_norm <- cp_list$vs_norm
    kd      <- getKnownDisease_vec(gene_name[idx])
    
    omim_match          <- match(gene_symbol[idx], omim_dt$approvedGeneSymbol)
    known_disease_label <- ifelse(is.na(omim_match), "", omim_dt$phenotype[omim_match])
    
    if(inheritance == "CmpHET") {
      order_score <- ave(cp, gene_symbol[idx],
                         FUN=function(x) mean(sort(x, decreasing=TRUE)[1:min(2,length(x))]))
    } else {
      order_score <- cp
    }
    
    df <- data.frame(
      CHROM             = variants$CHROM[idx],
      POS               = variants$POS[idx],
      REF               = variants$REF[idx],
      ALT               = variants$ALT[idx],
      FILTER            = variants$FILTER[idx],
      genesList         = gene_symbol[idx],
      gene_name         = gene_name[idx],
      pLI               = pLI[idx],
      pRec              = pRec[idx],
      lof_z             = lof_z[idx],
      mis_z             = mis_z[idx],
      clinvar           = clinvar[idx],
      knownDisease      = kd,
      knownDiseaseLabel = known_disease_label,
      biotype           = biotype[idx],
      Consequence       = consequence[idx],
      cDNA              = cdna[idx],
      Protein           = protein[idx],
      HIGH              = HIGH[idx],
      Splicing          = splicing[idx],
      MODERATE          = MODERATE[idx],
      CADD              = cadd[idx],
      C1KB              = C1KB[idx],
      gnomAD            = gnomAD[idx],
      freqInterna       = freqInterna_vec[idx],
      nCalled           = nCalled_vec[idx],
      AC_interna        = nAlleles_vec[idx],
      FunctPos          = FunctPos[idx],
      FunctScore        = FunctScore[idx],
      PhysPos           = PhysPos[idx],
      PhysScore         = PhysScore[idx],
      VariantScore      = vs_norm,
      ClinPriorScore    = cp,
      OrderScore        = order_score,
      GT                = variants$GT[idx],
      phaseGT           = phase_id_full[idx],
      GQ_DP_AD          = paste0(variants$GQ[idx], ":", variants$DP[idx], ":", variants$AD[idx]),
      inheritance       = inheritance,
      stringsAsFactors  = FALSE
    )
    
    if(splicingMode == "full") {
      df$acceptor_loss     <- acceptor_loss[idx]
      df$acceptor_loss_pos <- acceptor_loss_pos[idx]
      df$acceptor_gain     <- acceptor_gain[idx]
      df$acceptor_gain_pos <- acceptor_gain_pos[idx]
      df$donor_loss        <- donor_loss[idx]
      df$donor_loss_pos    <- donor_loss_pos[idx]
      df$donor_gain        <- donor_gain[idx]
      df$donor_gain_pos    <- donor_gain_pos[idx]
      df$splicing_vep      <- splicing_vep[idx]
    }
    
    df
  }
  
  # -- Build per-inheritance tables and merge --------------------------------
  tableHOM    <- constructTable(which(is_HOM & keep_AR), "HOM")
  tableAD     <- constructTable(which(is_HET & keep_AD), "HET")
  tableCMPHET <- constructTable(cmphet_idx,               "CmpHET")
  tableXL     <- constructTable(which(is_XL  & keep_AR), "XLink")
  
  tableEnsemble <- rbind(tableHOM, tableAD, tableCMPHET, tableXL)
  if(is.null(tableEnsemble) || nrow(tableEnsemble) == 0) return(data.frame())
  
  # -- Physical phasing: applied on CmpHET rows ------------------------------
  #
  # CIS/TRANS rules:
  #   - All phased variants in a gene share the SAME haplotype ID AND no
  #     unphased variant exists -> pure CIS -> remove entire gene.
  #   - All phased variants share the SAME haplotype ID BUT at least one
  #     unphased variant exists -> keep ALL (unphased may be in TRANS).
  #   - Phased variants have DIFFERENT haplotype IDs -> confirmed TRANS -> keep all.
  #   - < 2 variants with PID -> keep all (conservative).
  #
  # Note: GATK may write GT=0/1 but still populate PGT/PID in GT_full.
  # Phasing is always detected from GT_full, NOT GT.
  
  cmphet_rows <- tableEnsemble$inheritance == "CmpHET"
  if(any(cmphet_rows)) {
    cmphet_sub <- tableEnsemble[cmphet_rows, ]
    
    orig_idx <- match(
      paste(cmphet_sub$CHROM, cmphet_sub$POS, cmphet_sub$REF, cmphet_sub$ALT),
      paste(variants$CHROM,   variants$POS,   variants$REF,   variants$ALT)
    )
    
    gt_full_sub <- if(!is.null(variants$GT_full)) variants$GT_full[orig_idx] else variants$GT[orig_idx]
    
    m_pid     <- regexpr("\\d+_[ACGT*]+_[ACGT*]+", gt_full_sub, perl=TRUE)
    has_pid   <- m_pid > 0
    phase_ids <- rep(NA_character_, nrow(cmphet_sub))
    phase_ids[has_pid] <- regmatches(gt_full_sub, m_pid)
    
    cmphet_sub$phaseGT <- phase_ids
    # FIX: only update entries that have a PID to avoid overwriting values
    # already set by the het_all_idx block above
    phase_id_full[orig_idx[has_pid]] <- phase_ids[has_pid]
    
    keep_row <- rep(TRUE, nrow(cmphet_sub))
    
    for(g in unique(cmphet_sub$genesList[!is.na(cmphet_sub$genesList)])) {
      pos_g      <- which(cmphet_sub$genesList == g)
      ph_g       <- phase_ids[pos_g]
      ph_notna   <- ph_g[!is.na(ph_g)]
      n_unphased <- sum(is.na(ph_g))
      
      if(length(ph_notna) >= 2 && length(unique(ph_notna)) == 1) {
        if(n_unphased == 0) {
          keep_row[pos_g]                 <- FALSE
          cis_phased_out[orig_idx[pos_g]] <- TRUE
        }
      }
    }
    
    cmphet_sub <- cmphet_sub[keep_row, ]
    
    gene_counts <- table(cmphet_sub$genesList)
    keep_genes  <- names(gene_counts[gene_counts >= 2])
    cmphet_sub  <- cmphet_sub[cmphet_sub$genesList %in% keep_genes, ]
    
    tableEnsemble <- rbind(tableEnsemble[!cmphet_rows, ], cmphet_sub)
    if(nrow(tableEnsemble) == 0) return(data.frame())
  }
  
  # -- discard_zero_score filter ---------------------------------------------
  if(discard_zero_score) {
    tableEnsemble <- tableEnsemble[tableEnsemble$VariantScore > 0, ]
    if(nrow(tableEnsemble) == 0) return(data.frame())
  }
  
  # Sort by OrderScore (descending) and add rank column
  tableEnsemble <- tableEnsemble[order(tableEnsemble$OrderScore, decreasing=TRUE), ]
  tableEnsemble <- cbind(ClinPriorPosition=seq_len(nrow(tableEnsemble)), tableEnsemble)
  
  # -- Capture variables for traceVariant closure ----------------------------
  force(splicing); force(splicing_vep)
  force(acceptor_loss); force(acceptor_loss_pos)
  force(acceptor_gain); force(acceptor_gain_pos)
  force(donor_loss);    force(donor_loss_pos)
  force(donor_gain);    force(donor_gain_pos)
  force(dist_num)
  
  # -- Diagnostic function: trace a single variant through all filters/scores -
  traceVariant <- function(chrom, pos, ref, alt) {
    idx <- which(variants$CHROM == as.character(chrom) &
                   variants$POS   == as.character(pos)   &
                   variants$REF   == ref                 &
                   variants$ALT   == alt)
    
    if(length(idx) == 0) {
      cat("VARIANT NOT FOUND in the variants data.frame\n")
      return(invisible(NULL))
    }
    
    i <- idx[1]
    cat("=== VARIANT TRACE", chrom, pos, ref, alt, "===\n\n")
    cat("GT:          ", variants$GT[i], "\n")
    cat("biotype:     ", biotype[i], "\n")
    cat("impact:      ", impact[i], "\n")
    cat("consequence: ", consequence[i], "\n")
    cat("cDNA:        ", cdna[i], "\n")
    cat("distance (HGVSc):",
        ifelse(is.na(dist_num[i]), "NA (not intronic or UTR)", dist_num[i]),
        "bp to boundary\n")
    cat("clinvar:     ", clinvar[i], "\n")
    cat("gnomAD:      ", gnomAD[i], "\n")
    cat("freqInterna: ", freqInterna_vec[i], " | nCalled:", nCalled_vec[i], "\n")
    cat("AC_interna:  ", nAlleles_vec[i], "\n")
    cat("C1KB:        ", ifelse(assembly == "assembly38", C1KB[i], "NA (assembly37)"), "\n")
    cat("CADD:        ", cadd[i], "\n")
    cat("pLI:         ", pLI[i], "| pRec:", pRec[i], "\n")
    cat("lof_z:       ", lof_z[i], "| mis_z:", mis_z[i], "\n")
    cat("HIGH:        ", HIGH[i], "\n")
    cat("MODERATE:    ", MODERATE[i], "\n")
    cat("splicing:    ", splicing[i], "\n")
    cat("splicing_vep:", splicing_vep[i], "\n")
    cat("phaseGT:     ", ifelse(is.na(phase_id_full[i]), "NA (unphased)", phase_id_full[i]), "\n")
    cat("cisPhasedOut:", cis_phased_out[i],
        if(cis_phased_out[i]) "=> passed all filters but all CmpHET partners in CIS" else "", "\n")
    
    if(splicingMode == "full") {
      cat("acceptor_loss:", acceptor_loss[i], "@ pos:", acceptor_loss_pos[i], "\n")
      cat("acceptor_gain:", acceptor_gain[i], "@ pos:", acceptor_gain_pos[i], "\n")
      cat("donor_loss:   ", donor_loss[i],    "@ pos:", donor_loss_pos[i],    "\n")
      cat("donor_gain:   ", donor_gain[i],    "@ pos:", donor_gain_pos[i],    "\n")
    }
    
    cat("\n--- FILTERS ---\n")
    cat("[", if(is_coding[i]) "OK" else "FAIL", "] is_coding\n")
    cv_benign <- grepl("benign|likely_benign", clinvar[i], ignore.case=TRUE)
    cv_pathog <- grepl("^pathogenic|likely_pathogenic", clinvar[i], ignore.case=TRUE, perl=TRUE)
    # FIX: respectar discard_ClinVar_Benign al traceVariant
    cv_filter <- if(discard_ClinVar_Benign) (!cv_benign | cv_pathog) else TRUE
    cat("[", if(cv_filter) "OK" else "FAIL", "] keep_clinvar",
        "(benign:", cv_benign, "| pathog:", cv_pathog,
        "| discard_ClinVar_Benign:", discard_ClinVar_Benign, ")\n")
    cat("[", if(is.na(gnomAD[i]) | gnomAD[i] <= frequenceAR) "OK" else "FAIL",
        "] gnomAD <= frequenceAR (", frequenceAR, ") | value:", gnomAD[i], "\n")
    cat("[", if(is.na(gnomAD[i]) | gnomAD[i] <= frequenceAD) "OK" else "FAIL",
        "] gnomAD <= frequenceAD (", frequenceAD, ") | value:", gnomAD[i], "\n")
    fi_ok <- is.na(freqInterna_vec[i]) | is.na(nCalled_vec[i]) |
      nCalled_vec[i] < nCalledMin | freqInterna_vec[i] <= freqInterna
    cat("[", if(fi_ok) "OK" else "FAIL", "] keep_freqInterna",
        "(freqInterna:", freqInterna_vec[i], "| nCalled:", nCalled_vec[i], ")\n")
    cat("[", if(is_HOM[i]) "YES" else "no", "] is_HOM\n")
    cat("[", if(is_HET[i]) "YES" else "no", "] is_HET\n")
    cat("[", if(is_XL[i])  "YES" else "no", "] is_XL\n")
    
    cat("\n--- PHYSICAL PHASING (CmpHET) ---\n")
    cat("phaseGT:     ", ifelse(is.na(phase_id_full[i]), "NA (unphased or not CmpHET candidate)", phase_id_full[i]), "\n")
    cat("cisPhasedOut:", cis_phased_out[i],
        if(cis_phased_out[i]) "=> all CmpHET partners in CIS; gene excluded from CmpHET" else "", "\n")
    if(!is.na(phase_id_full[i])) {
      same_gene_idx <- which(gene_symbol == gene_symbol[i] & is_HET & keep_AR & seq_along(gene_symbol) != i)
      if(length(same_gene_idx) > 0) {
        cat("Other HET variants in same gene:\n")
        for(j in same_gene_idx) {
          phase_j <- phase_id_full[j]
          cat(sprintf("  POS=%s | phaseGT=%s | %s\n",
                      variants$POS[j],
                      ifelse(is.na(phase_j), "NA (unphased)", phase_j),
                      ifelse(!is.na(phase_j) & !is.na(phase_id_full[i]) & phase_j == phase_id_full[i],
                             "=> IN CIS (same haplotype)",
                             "=> IN TRANS (different haplotype or unphased)")))
        }
      } else {
        cat("  No other HET variants found in the same gene.\n")
      }
    }
    
    if(splicingMode == "full") {
      is_intr_i <- grepl("intron", consequence[i], ignore.case=TRUE)
      cat("\n--- FULL SPLICING SELECTION ---\n")
      cat("[", if(is_intr_i & !is.na(dist_num[i]) & abs(dist_num[i]) <= splicingDistance) "YES" else "no",
          sprintf("] intronic <= %d bp (HGVSc: %s)\n", splicingDistance,
                  ifelse(is.na(dist_num[i]), "NA", dist_num[i])))
      cat("[", if(splicing_vep[i] != "||") "YES" else "no",
          "] positive VEP splicing:", splicing_vep[i], "\n")
      if(!is.na(dist_num[i]) && abs(dist_num[i]) > 25 && is_intr_i)
        cat("  [INFO] Loss discarded: distance >25bp from boundary\n")
    }
    
    # FIX: respectar discard_ClinVar_Benign per keep_AR_i / keep_AD_i
    keep_AR_i <- is_coding[i] & (is.na(gnomAD[i]) | gnomAD[i] <= frequenceAR) & fi_ok & cv_filter
    keep_AD_i <- is_coding[i] & (is.na(gnomAD[i]) | gnomAD[i] <= frequenceAD) & fi_ok & cv_filter
    
    cat("\n--- INHERITANCE MODES THAT WOULD PASS ---\n")
    cat("[", if(is_HOM[i] & keep_AR_i) "YES" else "no", "] HOM\n")
    cat("[", if(is_HET[i] & keep_AD_i) "YES" else "no", "] HET (AD)\n")
    cat("[", if(is_XL[i]  & keep_AR_i) "YES" else "no", "] XLink\n")
    in_cmphet <- i %in% cmphet_idx
    cat("[", if(in_cmphet) "YES" else "no", "] CmpHET (pre-phasing)",
        if(!in_cmphet & is_HET[i] & keep_AR_i) "(HET passes AR but gene has <2 variants)" else "", "\n")
    in_final  <- paste(variants$CHROM[i], variants$POS[i], variants$REF[i], variants$ALT[i]) %in%
      paste(tableEnsemble$CHROM, tableEnsemble$POS, tableEnsemble$REF, tableEnsemble$ALT)
    cat("[", if(in_final) "YES" else "no", "] CmpHET (final table after phasing)\n")
    
    cat("\n--- DETAILED VARIANT SCORE ---\n")
    for(inh in c("HOM","HET","CmpHET","XLink")) {
      vs_i      <- calcScore(i, inh)
      cp_list_i <- calcClinPrior(vs_i, i, inh)
      cp_i      <- cp_list_i$cp
      vs_norm_i <- cp_list_i$vs_norm
      sp_vep_i  <- splicing_vep[i] != "||"
      sp_full_i <- splicing[i] != "||" & splicing[i] != "|||" & !sp_vep_i
      cat(sprintf("\n  [%s] VariantScore (raw): %.4f | VariantScore (norm): %.4f | ClinPriorScore: %.4f\n",
                  inh, vs_i, vs_norm_i, cp_i))
      cat(sprintf("    HIGH=%-5s  MODERATE=%-5s  sp_vep=%-5s  sp_full_only=%-5s\n",
                  HIGH[i] != ".", MODERATE[i] != ".", sp_vep_i, sp_full_i))
      cat(sprintf("    CADD=%-6.1f  C1KB=%-6s  pLI=%-6s  lof_z=%-6s\n",
                  ifelse(is.na(cadd[i]),  0,    cadd[i]),
                  ifelse(assembly != "assembly38" || is.na(C1KB[i]), "NA", round(C1KB[i], 2)),
                  ifelse(is.na(pLI[i]),   "NA", round(pLI[i],   3)),
                  ifelse(is.na(lof_z[i]), "NA", round(lof_z[i], 2))))
    }
    cat("\n")
    invisible(NULL)
  }
  
  gc()
  attr(tableEnsemble, "traceVariant") <- traceVariant
  return(tableEnsemble)
}